config/routes.rb
Rails.application.routes.draw do
  resources :user_products

  resources :products

  resources :product_categories

  devise_for :users

  ActiveAdmin.routes(self)

  resources :visitors

  root to: "visitors#index"

  get 'home' => 'home#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :author
  belongs_to :genre
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  has_many :books
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_category
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user_product.rb
class UserProduct < ActiveRecord::Base
  validates :user_id, :product_category_id, :product_id, presence:true
  belongs_to :user
  belongs_to :product_category
  belongs_to :product
end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  IDPROOF = { '1' => 'VoterID', '2' => 'PANCard', '3' => 'AaathorCard', '4' => 'DrivingLic', '5' => 'RationCard' }
  validates :first_name, :last_name, :sex, :age, :phone_no, :location, :reason, :contact_person, :id_proof, :id_number, presence: true
  validates :phone_no, :id_number, uniqueness: true
  before_create :set_auto_generate_number


  def name
    "#{first_name} #{last_name}"
  end

  def set_auto_generate_number
    random_token = rand.to_s[2..8]
    unless Visitor.find_by_auto_generate_id(random_token).nil?
      set_auto_generate_number
    else
      self.auto_generate_id = random_token
    end
  end

  def as_json(options={})
    super()
  end

  def self.search(params={})
    search = params[:search]
    if search && !search.empty?
      where("first_name LIKE ? OR last_name LIKE ? OR sex LIKE ? OR age LIKE ? OR phone_no LIKE ? OR location LIKE ? OR contact_person LIKE ? OR id_number LIKE ?",
            "%#{search}%", "%#{search}%","%#{search}%", "%#{search}%","%#{search}%", "%#{search}%","%#{search}%", "%#{search}%")
    else
      all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  after_action :set_csrf_cookie_for_ng

  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  def authenticate_active_admin_user!
    authenticate_user!
    unless current_user.superadmin?
      flash[:alert] = "Unauthorized Access!"
      redirect_to root_path
    end
  end

  protected

  def verified_request?
    super || valid_authenticity_token?(session, request.headers['X-XSRF-TOKEN'])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'
  def index

  end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < InheritedResources::Base

  private

    def product_category_params
      params.require(:product_category).permit(:name)
    end
end

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base

  private

    def product_params
      params.require(:product).permit(:name, :product_category_id)
    end
end

app/controllers/user_products_controller.rb
class UserProductsController < InheritedResources::Base

  private

    def user_product_params
      params.require(:user_product).permit(:user_id, :product_category_id, :product_id, :order_date)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_visitor, only:[:update]
  respond_to :json,:html

  def index
    @visitors = Visitor.search(params)
    respond_to do |format|
      format.json { render json: @visitors }
      format.html
    end
  end

  def create
    @visitor = Visitor.new(visitor_params)
    if @visitor.save
      render json: @visitor, status: :ok
    else
      render json: {visitor_errors: @visitor.errors.full_messages, status: :no_content}
    end
  end

  def destroy
    respond_with Visitor.destroy(params[:id])
  end

  def update
    if @visitor.update(visitor_params)
      render json: @visitor, status: :ok
    else
      render json: {visitor_errors: @visitor.errors.full_messages, status: :no_content}
    end
  end

  private
  def visitor_params
    params.require(:visitor).permit(:id, :first_name, :last_name, :sex, :age, :phone_no, :location, :reason, :contact_person, :id_proof, :id_number, :auto_generate_id, :created_at,:updated_at) unless params[:visitor].empty?
  end

  def get_visitor
    @visitor = Visitor.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def remote_get(path,target_tag_id)
    "$.post('/admin/user_products/dynamic_select?#{path}=' + $('##{path}').val(),
            function(data) {$('##{target_tag_id}').html(data);$('##{target_tag_id}').select2('data', null);}
    );"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_products_helper.rb
module UserProductsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AngularBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 sidebar">
        <h3>Sidebar</h3>
        <ul class="nav nav-list">
          <li><%= link_to "Visitor Creation", visitors_path %></li>
          <li><%= link_to "Admin System", "admin/dashboard#index" %></li>
          <li><%= link_to "Products", "#" %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        </ul>
      </div>
      <div class="col-md-9 col-md-offset-3 content">
        <%= yield %>
      </div>
    </div>
  </div>
<% else %>
    <div class="container">
      <div class="row">
        <div class="span9"><%= yield %></div>
      </div>
    </div>
<% end %>

</body>
</html>

<style>

  html, body, .container-fluid, .row {
    height: 100%;
  }
  .sidebar {
    background-color: #CCCCCC;
  }

  @media (min-width: 992px) {
    .sidebar {
      position: fixed;
      top: 0;
      left: 0;
      bottom: 0;
      z-index: 1000;
      display: block;
      background-color: #CCCCCC;
    }
  }
</style>

app/views/product_categories/_form.html.erb
<%= form_for(@product_category) do |f| %>
  <% if @product_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_category.errors.count, "error") %> prohibited this product_category from being saved:</h2>

      <ul>
      <% @product_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_categories/edit.html.erb
<h1>Editing Product Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_category %> |
<%= link_to 'Back', product_categories_path %>

app/views/product_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Product Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_categories.each do |product_category| %>
      <tr>
        <td><%= product_category.name %></td>
        <td><%= link_to 'Show', product_category %></td>
        <td><%= link_to 'Edit', edit_product_category_path(product_category) %></td>
        <td><%= link_to 'Destroy', product_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product category', new_product_category_path %>

app/views/product_categories/new.html.erb
<h1>New Product Category</h1>

<%= render 'form' %>

<%= link_to 'Back', product_categories_path %>

app/views/product_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_category.name %>
</p>

<%= link_to 'Edit', edit_product_category_path(@product_category) %> |
<%= link_to 'Back', product_categories_path %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :product_category_id %><br>
    <%= f.number_field :product_category_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Product category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.product_category_id %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Product category:</strong>
  <%= @product.product_category_id %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/user_products/_form.html.erb
<%= form_for(@user_product) do |f| %>
  <% if @user_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_product.errors.count, "error") %> prohibited this user_product from being saved:</h2>

      <ul>
      <% @user_product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :product_category_id %><br>
    <%= f.number_field :product_category_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br>
    <%= f.text_field :order_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_products/edit.html.erb
<h1>Editing User Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_product %> |
<%= link_to 'Back', user_products_path %>

app/views/user_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Products</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Product category</th>
      <th>Product</th>
      <th>Order date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_products.each do |user_product| %>
      <tr>
        <td><%= user_product.user_id %></td>
        <td><%= user_product.product_category_id %></td>
        <td><%= user_product.product_id %></td>
        <td><%= user_product.order_date %></td>
        <td><%= link_to 'Show', user_product %></td>
        <td><%= link_to 'Edit', edit_user_product_path(user_product) %></td>
        <td><%= link_to 'Destroy', user_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User product', new_user_product_path %>

app/views/user_products/new.html.erb
<h1>New User Product</h1>

<%= render 'form' %>

<%= link_to 'Back', user_products_path %>

app/views/user_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_product.user_id %>
</p>

<p>
  <strong>Product category:</strong>
  <%= @user_product.product_category_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @user_product.product_id %>
</p>

<p>
  <strong>Order date:</strong>
  <%= @user_product.order_date %>
</p>

<%= link_to 'Edit', edit_user_product_path(@user_product) %> |
<%= link_to 'Back', user_products_path %>

app/views/visitors/_form.html.erb
<form name="VisitorForm" ng-submit="addVisitor()" novalidate>
  <div class="row form-group required">
    <label class="col-md-2 control-label">FirstName</label>
    <div class="col-xs-4">
      <input type="text" ng-model="newVisitor.first_name" class="form-control" placeholder="First Name" server-error/>
    </div>
    <label class="col-md-2 control-label">LastName</label>
    <div class="col-xs-4">
      <input type="text" ng-model="newVisitor.last_name" class="form-control" placeholder="Last Name" />
    </div>
  </div>

  <div class="row form-group required">
    <label class="col-md-2 control-label">Sex</label>
    <div class="col-xs-4">
      <select ng-model="newVisitor.sex" class="form-control" placeholder="Sex">
        <option value="">Sex</option>
        <option value="male">Male</option>
        <option value="female">Female</option>
      </select>
    </div>
    <label class="col-md-2 control-label">Age</label>
    <div class="col-xs-4">
      <input type="text" ng-model="newVisitor.age" class="form-control" placeholder="Age" />
    </div>
  </div>

  <div class="row form-group required">
    <label class="col-md-2 control-label">PhoneNo</label>
    <div class="col-xs-4">
      <input type="text" ng-model="newVisitor.phone_no" class="form-control" placeholder="PhoneNo" />
    </div>
    <label class="col-md-2 control-label">Location</label>
    <div class="col-xs-4">
      <input type="text" ng-model="newVisitor.location" class="form-control" placeholder="Location" />
    </div>
  </div>

  <div class="row form-group required">
    <label class="col-md-2 control-label">Reason for Visit</label>
    <div class="col-xs-4">
      <input type="text" ng-model="newVisitor.reason" class="form-control" placeholder="Reason for Visit" />
    </div>
    <label class="col-md-2 control-label">Contact Person</label>
    <div class="col-xs-4">
      <input type="text" ng-model="newVisitor.contact_person" class="form-control" placeholder="Contact Person" />
    </div>
  </div>

  <div class="row form-group required">
    <label class="col-md-2 control-label">ID Proof</label>
    <div class="col-xs-4">
      <select ng-model="newVisitor.id_proof" class="form-control" placeholder="ID Proof">
        <option value="">ID Proof</option>
        <option value="1">VoterID</option>
        <option value="2">PANCard</option>
        <option value="3">AaathorCard</option>
        <option value="4">DrivingLic</option>
        <option value="5">RationCard</option>
      </select>
    </div>
    <label class="col-md-2 control-label">ID Number</label>
    <div class="col-xs-4">
      <input type="text" ng-model="newVisitor.id_number" class="form-control" placeholder="ID Number" />
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 text-center">
      <br />
      <input type="Submit" value="Save Visitor" class="btn btn-primary"  />
    </div>
  </div>
</form>


<style>

  .form-group.required .control-label:after{
    content:"*";
    color:red;
  }

</style>

app/views/visitors/create.html.erb
<h1>Visitors#create</h1>
<p>Find me in app/views/visitors/create.html.erb</p>

app/views/visitors/destroy.html.erb
<h1>Visitors#destroy</h1>
<p>Find me in app/views/visitors/destroy.html.erb</p>

app/views/visitors/index.html.erb
<div class="container" ng-app="VisitorCenter">
  <h1>Visitors</h1>

  <div ng-controller="visitorsController">
    <div class="well">
      <h3>Add a new Visitor</h3>
      <%= render 'form' %>
    </div>

    <h3>Currently Visiting</h3>
    <hr />
    <table class="table table-bordered table-striped">

      <div class="row">
        <div class="col-lg-6">
          <div class="input-group">
            <input type="text" class="form-control search-query" placeholder="Search" name="query" ng-model="query">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button" ng-click="searchVisitor()">Go!</button>
              </span>
          </div>
        </div>
      </div>
      <br/>
      <thead>
      <tr>
        <th>Name</th>
        <th>Sex</th>
        <th>Age</th>
        <th>PhoneNo</th>
        <th>Location</th>
        <th>Reason For Visit</th>
        <th>ContactPerson</th>
        <th>IDProof</th>
        <th>IDNumber</th>
        <th>GatePass</th>
        <th>LoginDate</th>
        <th>&nbsp;</th>
      </tr>
      </thead>
      <tbody>
      <tr ng-show="!visitors.length">
        <td colspan="4">No visitors in the building.</td>
      </tr>
      <tr ng-repeat="visitor in visitors">
        <td>{{ visitor.first_name + " " + visitor.last_name }}</td>
        <td>{{ visitor.sex }}</td>
        <td>{{ visitor.age }}</td>
        <td>{{ visitor.phone_no }}</td>
        <td>{{ visitor.location }}</td>
        <td>{{ visitor.reason }}</td>
        <td>{{ visitor.contact_person }}</td>
        <td>{{ visitor.id_proof }}</td>
        <td>{{ visitor.id_number }}</td>
        <td>{{ visitor.auto_generate_id }}</td>
        <td>{{ visitor.created_at | date:"MM/dd/yyyy" }}</td>
        <td><a class="btn btn-primary" href="" ng-click="editVisitor($index)">Edit</a> | <a href="" class="btn btn-danger" ng-click="deleteVisitor($index)">Remove</a></td>
      </tr>
      </tbody>
    </table>

  </div>
</div>